using System;
using System.Collections.Frozen;
using System.Collections.Generic;

namespace OutbreakTracker2.App.Services.TextureAtlas;

public class TextureAtlasInfo
{
    public List<TextureFrame> Frames { get; set; }
    public FrozenDictionary<string, int> FrameIndex { get; private set; }
    public int SheetContentWidth { get; set; }
    public int SheetContentHeight { get; set; }

    private TextureAtlasInfo()
    {
        Frames = [];
        FrameIndex = FrozenDictionary<string, int>.Empty;
    }

    /// <summary>
    /// Creates and populates a TextureAtlasInfo object with data from the provided Lua code.
    /// In a production application, this data would typically be loaded from a JSON/XML file
    /// generated by a tool like TexturePacker.
    /// </summary>
    public static TextureAtlasInfo CreateFromLuaData()
    {
        TextureAtlasInfo info = new();
        Dictionary<string, int> tempFrameIndex = new(StringComparer.OrdinalIgnoreCase);

        info.Frames.Add(new TextureFrame { X = 830, Y = 784, Width = 256, Height = 192 }); // 1: below freezing point
        info.Frames.Add(new TextureFrame { X = 0, Y = 0, Width = 256, Height = 256 });     // 2: bustAlyssa
        info.Frames.Add(new TextureFrame { X = 0, Y = 256, Width = 256, Height = 256 });   // 3: bustCindy
        info.Frames.Add(new TextureFrame { X = 0, Y = 512, Width = 256, Height = 256 });   // 4: bustDavid
        info.Frames.Add(new TextureFrame { X = 0, Y = 768, Width = 256, Height = 256 });   // 5: bustGeorge
        info.Frames.Add(new TextureFrame { X = 0, Y = 1024, Width = 256, Height = 256 });  // 6: bustJim
        info.Frames.Add(new TextureFrame { X = 256, Y = 0, Width = 256, Height = 256 });   // 7: bustKevin
        info.Frames.Add(new TextureFrame { X = 512, Y = 0, Width = 256, Height = 256 });   // 8: bustMark
        info.Frames.Add(new TextureFrame { X = 768, Y = 0, Width = 256, Height = 256 });   // 9: bustYoko
        info.Frames.Add(new TextureFrame { X = 436, Y = 576, Width = 30, Height = 11 });   // 10: dead
        info.Frames.Add(new TextureFrame { X = 512, Y = 844, Width = 256, Height = 192 }); // 11: decisions,decisions
        info.Frames.Add(new TextureFrame { X = 1024, Y = 0, Width = 256, Height = 196 });  // 12: desperate times
        info.Frames.Add(new TextureFrame { X = 1024, Y = 196, Width = 256, Height = 196 });// 13: elimination 1
        info.Frames.Add(new TextureFrame { X = 256, Y = 256, Width = 256, Height = 196 }); // 14: elimination 2
        info.Frames.Add(new TextureFrame { X = 512, Y = 256, Width = 256, Height = 196 }); // 15: elimination 3
        info.Frames.Add(new TextureFrame { X = 768, Y = 256, Width = 256, Height = 196 }); // 16: end of the road
        info.Frames.Add(new TextureFrame { X = 946, Y = 452, Width = 39, Height = 15 });  // 17: equip
        info.Frames.Add(new TextureFrame { X = 1024, Y = 392, Width = 256, Height = 196 });// 18: flashback
        info.Frames.Add(new TextureFrame { X = 436, Y = 560, Width = 95, Height = 16 });  // 19: healthmask
        info.Frames.Add(new TextureFrame { X = 512, Y = 1036, Width = 256, Height = 192 });// 20: hellfire
        info.Frames.Add(new TextureFrame { X = 256, Y = 560, Width = 20, Height = 20 });  // 21: iconAlyssa
        info.Frames.Add(new TextureFrame { X = 276, Y = 560, Width = 20, Height = 20 });  // 22: iconCindy
        info.Frames.Add(new TextureFrame { X = 296, Y = 560, Width = 20, Height = 20 });  // 23: iconDavid
        info.Frames.Add(new TextureFrame { X = 316, Y = 560, Width = 20, Height = 20 });  // 24: iconGeorge
        info.Frames.Add(new TextureFrame { X = 336, Y = 560, Width = 20, Height = 20 });  // 25: iconJim
        info.Frames.Add(new TextureFrame { X = 356, Y = 560, Width = 20, Height = 20 });  // 26: iconKevin
        info.Frames.Add(new TextureFrame { X = 376, Y = 560, Width = 20, Height = 20 });  // 27: iconMark
        info.Frames.Add(new TextureFrame { X = 396, Y = 560, Width = 20, Height = 20 });  // 28: iconNPC
        info.Frames.Add(new TextureFrame { X = 416, Y = 560, Width = 20, Height = 20 });  // 29: iconYoko
        info.Frames.Add(new TextureFrame { X = 256, Y = 452, Width = 210, Height = 108 }); // 30: invDouble
        info.Frames.Add(new TextureFrame { X = 834, Y = 488, Width = 96, Height = 98 });  // 31: inventorymask
        info.Frames.Add(new TextureFrame { X = 466, Y = 452, Width = 112, Height = 108 }); // 32: invSingle
        info.Frames.Add(new TextureFrame { X = 512, Y = 608, Width = 62, Height = 56 });  // 33: invSpecial
        info.Frames.Add(new TextureFrame { X = 531, Y = 560, Width = 46, Height = 48 });  // 34: ispecialmask
        info.Frames.Add(new TextureFrame { X = 768, Y = 976, Width = 256, Height = 192 });// 35: outbreak
        info.Frames.Add(new TextureFrame { X = 256, Y = 588, Width = 256, Height = 196 });// 36: showdown 1
        info.Frames.Add(new TextureFrame { X = 578, Y = 452, Width = 256, Height = 196 });// 37: showdown 2
        info.Frames.Add(new TextureFrame { X = 834, Y = 588, Width = 256, Height = 196 });// 38: showdown 3
        info.Frames.Add(new TextureFrame { X = 834, Y = 452, Width = 112, Height = 36 }); // 39: statusbar
        info.Frames.Add(new TextureFrame { X = 1024, Y = 976, Width = 256, Height = 192 });// 40: the hive
        info.Frames.Add(new TextureFrame { X = 574, Y = 648, Width = 256, Height = 196 });// 41: training ground
        info.Frames.Add(new TextureFrame { X = 256, Y = 784, Width = 256, Height = 196 });// 42: underbelly
        info.Frames.Add(new TextureFrame { X = 512, Y = 576, Width = 15, Height = 15 });  // 43: virus50
        info.Frames.Add(new TextureFrame { X = 512, Y = 591, Width = 15, Height = 15 });  // 44: virus80
        info.Frames.Add(new TextureFrame { X = 985, Y = 452, Width = 15, Height = 15 });  // 45: virus90
        info.Frames.Add(new TextureFrame { X = 1000, Y = 452, Width = 15, Height = 15 }); // 46: virusOK
        info.Frames.Add(new TextureFrame { X = 256, Y = 980, Width = 256, Height = 196 });// 47: wild things
        info.Frames.Add(new TextureFrame { X = 946, Y = 467, Width = 20, Height = 20 });  // 48: key
        info.Frames.Add(new TextureFrame { X = 768, Y = 1172, Width = 300, Height = 24 });// 49: title bar
        info.Frames.Add(new TextureFrame { X = 768, Y = 1200, Width = 300, Height = 30 });// 50: slot bar

        tempFrameIndex["below freezing point"] = 0;
        tempFrameIndex["bustAlyssa "] = 1;
        tempFrameIndex["bustCindy "] = 2;
        tempFrameIndex["bustDavid "] = 3;
        tempFrameIndex["bustGeorge "] = 4;
        tempFrameIndex["bustJim "] = 5;
        tempFrameIndex["bustKevin "] = 6;
        tempFrameIndex["bustMark "] = 7;
        tempFrameIndex["bustYoko "] = 8;
        tempFrameIndex["bustAlyssa"] = 1; // Duplicate entry in Lua, pointing to same frame
        tempFrameIndex["bustCindy"] = 2;
        tempFrameIndex["bustDavid"] = 3;
        tempFrameIndex["bustGeorge"] = 4;
        tempFrameIndex["bustJim"] = 5;
        tempFrameIndex["bustKevin"] = 6;
        tempFrameIndex["bustMark"] = 7;
        tempFrameIndex["bustYoko"] = 8;
        tempFrameIndex["dead"] = 9;
        tempFrameIndex["decisions,decisions"] = 10;
        tempFrameIndex["desperate times"] = 11;
        tempFrameIndex["elimination 1"] = 12;
        tempFrameIndex["elimination 2"] = 13;
        tempFrameIndex["elimination 3"] = 14;
        tempFrameIndex["end of the road"] = 15;
        tempFrameIndex["equip"] = 16;
        tempFrameIndex["flashback"] = 17;
        tempFrameIndex["healthmask"] = 18;
        tempFrameIndex["hellfire"] = 19;
        tempFrameIndex["iconAlyssa"] = 20;
        tempFrameIndex["iconCindy"] = 21;
        tempFrameIndex["iconDavid"] = 22;
        tempFrameIndex["iconGeorge"] = 23;
        tempFrameIndex["iconJim"] = 24;
        tempFrameIndex["iconKevin"] = 25;
        tempFrameIndex["iconMark"] = 26;
        tempFrameIndex["iconNPC"] = 27;
        tempFrameIndex["iconYoko"] = 28;
        tempFrameIndex["bustUnknown"] = 6; // All these map to bustKevin (index 6)
        tempFrameIndex["bustAL:B"] = 6;
        tempFrameIndex["bustBILLY"] = 6;
        tempFrameIndex["bustBONE"] = 6;
        tempFrameIndex["bustCONRAD"] = 6;
        tempFrameIndex["bustDANNY"] = 6;
        tempFrameIndex["bustDANNY:B"] = 6;
        tempFrameIndex["bustDUSTIN"] = 6;
        tempFrameIndex["bustHUNK"] = 6;
        tempFrameIndex["bustHUNK:B"] = 6;
        tempFrameIndex["bustKARL"] = 6;
        tempFrameIndex["bustLUKE"] = 6;
        tempFrameIndex["bustMIGUEL"] = 6;
        tempFrameIndex["bustMr.RED"] = 6;
        tempFrameIndex["bustRAYMOND"] = 6;
        tempFrameIndex["bustRODNEY"] = 6;
        tempFrameIndex["bustAARON"] = 7; // All these map to bustMark (index 7)
        tempFrameIndex["bustARNOLD"] = 7;
        tempFrameIndex["bustAUSTIN"] = 7;
        tempFrameIndex["bustAXEMAN"] = 7;
        tempFrameIndex["bustBOB"] = 7;
        tempFrameIndex["bustCLINT"] = 7;
        tempFrameIndex["bustDON"] = 7;
        tempFrameIndex["bustELLIOTT"] = 7;
        tempFrameIndex["bustGILL"] = 7;
        tempFrameIndex["bustGILL:B"] = 7;
        tempFrameIndex["bustMARVIN"] = 7;
        tempFrameIndex["bustMr.GOLD"] = 7;
        tempFrameIndex["bustTONY"] = 7;
        tempFrameIndex["bustANDY"] = 5; // All these map to bustJim (index 5)
        tempFrameIndex["bustCHUCK"] = 5;
        tempFrameIndex["bustDEREK"] = 5;
        tempFrameIndex["bustJEAN"] = 5;
        tempFrameIndex["bustKURT:B"] = 5;
        tempFrameIndex["bustMATTHEW"] = 5;
        tempFrameIndex["bustMICKEY"] = 5;
        tempFrameIndex["bustMr.GREEN"] = 5;
        tempFrameIndex["bustPETER"] = 5;
        tempFrameIndex["bustSAMUEL"] = 5;
        tempFrameIndex["bustWILL"] = 5;
        tempFrameIndex["bustAL"] = 4; // All these map to bustGeorge (index 4)
        tempFrameIndex["bustAL:C"] = 4;
        tempFrameIndex["bustARTHUR"] = 4;
        tempFrameIndex["bustCARTER"] = 4;
        tempFrameIndex["bustDORIAN"] = 4;
        tempFrameIndex["bustETHAN"] = 4;
        tempFrameIndex["bustFRANK"] = 4;
        tempFrameIndex["bustFRED"] = 4;
        tempFrameIndex["bustFROST"] = 4;
        tempFrameIndex["bustFROST:B"] = 4;
        tempFrameIndex["bustGARY"] = 4;
        tempFrameIndex["bustGARY:B"] = 4;
        tempFrameIndex["bustGREG"] = 4;
        tempFrameIndex["bustHARRY"] = 4;
        tempFrameIndex["bustHARSH"] = 4;
        tempFrameIndex["bustHOWARD"] = 4;
        tempFrameIndex["bustISAAC"] = 4;
        tempFrameIndex["bustJAKE"] = 4;
        tempFrameIndex["bustKEITH"] = 4;
        tempFrameIndex["bustKURT"] = 4;
        tempFrameIndex["bustLEN"] = 4;
        tempFrameIndex["bustMACDOWELL"] = 4;
        tempFrameIndex["bustMATT"] = 4;
        tempFrameIndex["bustMr.BLUE"] = 4;
        tempFrameIndex["bustNICOLAS"] = 4;
        tempFrameIndex["bustPATRICK"] = 4;
        tempFrameIndex["bustRICHARD"] = 4;
        tempFrameIndex["bustSEAN"] = 4;
        tempFrameIndex["bustBEN"] = 3; // All these map to bustDavid (index 3)
        tempFrameIndex["bustERIC"] = 3;
        tempFrameIndex["bustLLOYD"] = 3;
        tempFrameIndex["bustAXEMAN "] = 3;
        tempFrameIndex["bustMr.BLACK"] = 3;
        tempFrameIndex["bustNATHAN"] = 3;
        tempFrameIndex["bustPHILIP"] = 3;
        tempFrameIndex["bustROBERT"] = 3;
        tempFrameIndex["bustRODRIGUEZ"] = 3;
        tempFrameIndex["bustROGER"] = 3;
        tempFrameIndex["bustELENA"] = 1; // All these map to bustAlyssa (index 1)
        tempFrameIndex["bustKATE"] = 1;
        tempFrameIndex["bustLAURA"] = 1;
        tempFrameIndex["bustMONICA"] = 1;
        tempFrameIndex["bustMs.WHITE"] = 1;
        tempFrameIndex["bustREGAN"] = 1;
        tempFrameIndex["bustRITA"] = 1;
        tempFrameIndex["bustYOKO:Z"] = 8; // All these map to bustYoko (index 8)
        tempFrameIndex["bustAMELIA"] = 8;
        tempFrameIndex["bustMs.PEACH"] = 8;
        tempFrameIndex["bustREGAN:B"] = 8;
        tempFrameIndex["bustDOROTHY"] = 2; // All these map to bustCindy (index 2)
        tempFrameIndex["bustGINGER"] = 2;
        tempFrameIndex["bustKATHY"] = 2;
        tempFrameIndex["bustLINDA"] = 2;
        tempFrameIndex["bustMARY"] = 2;
        tempFrameIndex["bustMs.WATER"] = 2;
        tempFrameIndex["invDouble"] = 29;
        tempFrameIndex["inventorymask"] = 30;
        tempFrameIndex["invSingle"] = 31;
        tempFrameIndex["invSpecial"] = 32;
        tempFrameIndex["ispecialmask"] = 33;
        tempFrameIndex["outbreak"] = 34;
        tempFrameIndex["showdown 1"] = 35;
        tempFrameIndex["showdown 2"] = 36;
        tempFrameIndex["showdown 3"] = 37;
        tempFrameIndex["statusbar"] = 38;
        tempFrameIndex["the hive"] = 39;
        tempFrameIndex["training ground"] = 40;
        tempFrameIndex["underbelly"] = 41;
        tempFrameIndex["virus50"] = 42;
        tempFrameIndex["virus80"] = 43;
        tempFrameIndex["virus90"] = 44;
        tempFrameIndex["virusOK"] = 45;
        tempFrameIndex["wild things"] = 46;
        tempFrameIndex["key"] = 47;
        tempFrameIndex["title bar"] = 48;
        tempFrameIndex["slot bar"] = 49;

        info.SheetContentWidth = 1280;
        info.SheetContentHeight = 1280;
        info.FrameIndex = tempFrameIndex.ToFrozenDictionary();

        return info;
    }
}